// doc 相关错误范围 1400-1699
export const DocExceptionCode = {
  GENERAL_DOC_NOT_FOUND: 1400,
  GENERAL_DOC_CREATE_BUT_NOT_FOUND_USER: 1401,
  GENERAL_DOC_CREATE_BUT_NOT_FOUND_PARENT_FOLDER: 1402,
} as const
