// doc 相关错误范围 1400-1699
export const DocExceptionCode = {
  // general doc
  GENERAL_DOC_NOT_FOUND: 1400,
  GENERAL_DOC_CREATE_BUT_NOT_FOUND_USER: 1401,
  GENERAL_DOC_CREATE_BUT_NOT_FOUND_PARENT_FOLDER: 1402,
  CURRENT_USER_CAN_NOT_READ_THIS_GENERAL_DOC: 1403,
  CURRENT_USER_CAN_NOT_WRITE_THIS_GENERAL_DOC: 1404,
  CURRENT_USER_CAN_NOT_MANAGE_THIS_GENERAL_DOC: 1405,
  GENERAL_DOC_ADMINISTRATOR_ROLE_NOT_FOUND: 1406,
  GENERAL_DOC_COLLABORATOR_ROLE_NOT_FOUND: 1407,
  GENERAL_DOC_READER_ROLE_NOT_FOUND: 1408,

  // wiki doc
  WIKI_DOC_NOT_FOUND: 1450,
  WIKI_DOC_CREATE_BUT_NOT_FOUND_USER: 1451,
  WIKI_DOC_CREATE_BUT_NOT_FOUND_PARENT_USER: 1452,
  CURRENT_USER_CAN_NOT_READ_THIS_WIKI_DOC: 1453,
  CURRENT_USER_CAN_NOT_WRITE_THIS_WIKIL_DOC: 1454,
  CURRENT_USER_CAN_NOT_MANAGE_THIS_WIKI_DOC: 1455,
  WIKI_DOC_ADMINISTRATOR_ROLE_NOT_FOUND: 1456,
  WIKI_DOC_COLLABORATOR_ROLE_NOT_FOUND: 1457,
  WIKI_DOC_READER_ROLE_NOT_FOUND: 1458,

  // folder
  FOLDER_NOT_FOUND: 1500,
  FOLDER_CREATE_BUT_NOT_FOUND_USER: 1501,
  FOLDER_CREATE_BUT_NOT_FOUND_PARENT_FOLDER: 1502,
  CURRENT_USER_CAN_NOT_READ_THIS_FOLDER: 1503,
  CURRENT_USER_CAN_NOT_WRITE_THIS_FOLDER: 1504,
  CURRENT_USER_CAN_NOT_MANAGE_THIS_FOLDER: 1505,
  FOLDER_ADMINISTRATOR_ROLE_NOT_FOUND: 1506,
  FOLDER_COLLABORATOR_ROLE_NOT_FOUND: 1507,
  FOLDER_READER_ROLE_NOT_FOUND: 1508,
} as const
