// doc 相关错误范围 1400-1699
export const DocExceptionCode = {
  // general doc
  GENERAL_DOC_NOT_FOUND: 1400,
  GENERAL_DOC_CREATE_BUT_NOT_FOUND_USER: 1401,
  GENERAL_DOC_CREATE_BUT_NOT_FOUND_PARENT_FOLDER: 1402,
  CURRENT_USER_CAN_NOT_READ_THIS_GENERAL_DOC: 1403,
  CURRENT_USER_CAN_NOT_WRITE_THIS_GENERAL_DOC: 1404,
  CURRENT_USER_CAN_NOT_MANAGE_THIS_GENERAL_DOC: 1405,

  // wiki doc
  WIKI_DOC_NOT_FOUND: 1406,
  WIKI_DOC_CREATE_BUT_NOT_FOUND_USER: 1407,
  WIKI_DOC_CREATE_BUT_NOT_FOUND_PARENT_USER: 1408,
  CURRENT_USER_CAN_NOT_READ_THIS_WIKI_DOC: 1409,
  CURRENT_USER_CAN_NOT_WRITE_THIS_WIKIL_DOC: 1410,
  CURRENT_USER_CAN_NOT_MANAGE_THIS_WIKI_DOC: 1411,

  // folder
  FOLDER_NOT_FOUND: 1412,
  FOLDER_CREATE_BUT_NOT_FOUND_USER: 1413,
  FOLDER_CREATE_BUT_NOT_FOUND_PARENT_FOLDER: 1414,
  CURRENT_USER_CAN_NOT_READ_THIS_FOLDER: 1415,
  CURRENT_USER_CAN_NOT_WRITE_THIS_FOLDER: 1416,
  CURRENT_USER_CAN_NOT_MANAGE_THIS_FOLDER: 1417,
} as const
